### ISSUE TITLE
Unable to create repository.

### ISSUE THREAD

**Issue by darklore** [line/centraldogma-go#29]
Hello.

I tried to create a project via dogma cli but it failed with following error.

```
$ ./dogma -c http://127.0.0.1:36462 new foooo
failed to parse a JSON document: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "creator" (class com.linecorp.centraldogma.internal.api.v1.CreateProjectRequest), not marked as ignorable (3 known properties: "owners", "members", "name"])
 at [Source: (String)"{"name":"foooof","creator":{}}
"; line: 1, column: 31] (through reference chain: com.linecorp.centraldogma.internal.api.v1.CreateProjectRequest["creator"]) (status: 400)
```

My environment:
centraldogma : 0.39.1
centraldogma-go: master branch (c07c29a)

Regards.

**Comment by linxGnu** [comment]
cc @minwoox Could you please take a look on this issue

**Comment by minwoox** [comment]
Oops, there're bugs in project_service and repository_service. Will send a fixing PR tomorrow. 🙇

**Comment by linxGnu** [comment]
User is using CLI. I reopened this issue until we merge https://github.com/line/centraldogma-go/pull/31
and attach new compiled cli along with CentralDogma Release package.

**Comment by hyangtack** [comment]
Hi, @linxGnu . I updated the binary of 0.39.2 in the Github.
https://github.com/line/centraldogma/releases/tag/centraldogma-0.39.2

If you have any problem, please reopen this issue. Thank you!
