### ISSUE TITLE
dogma returns error invalid json when called dogma cat --jsonpath

### ISSUE THREAD

**Issue by wingyplus** [line/centraldogma-go#36]
These steps below I copied from [tutorial](https://line.github.io/centraldogma/client-cli.html).

## Reproduce steps:

start centraldogma with docker command:

```
$ docker run -p 36462:36462 --name dogma --rm line/centraldogma
```

Then running with following steps:

```
$ cat test.sh
#!/bin/sh

conn='http://localhost:36462'

./dogma -c $conn new projFoo
./dogma -c $conn new projFoo/repoA
echo '{"a":"b"}' > a.json
./dogma -c $conn put projFoo/repoA/samples/a.json a.json -m 'Add a.json'
./dogma -c $conn ls
./dogma -c $conn cat projFoo/repoA/samples/a.json
./dogma -c $conn cat --jsonpath '$.a' projFoo/repoA/samples/a.json
```

## Expected result: 

The `./dogma -c http://localhost:36462 cat --jsonpath '$.a'` in the last step should returns `"b"` as mentioned in tutorial website.

## Actual Result

```
invalid character 'b' looking for beginning of value
```

## Dogma version:

```
$ ./dogma
Central Dogma version 0.41.1 (241c5a8)
```

And found it in current master branch.

**Comment by minwoox** [comment]
Thanks for the report. Let me take a look it soon.

**Comment by wingyplus** [comment]
I capturing response body:

```
{"revision":2,"path":"/samples/a.json","type":"JSON","content":"b","url":"/api/v1/projects/projFoo/repos/repoA/contents/samples/a.json"}
```

The content return `"b"` as type string. If we want to return `"b"` as tutorial mentioned, content must be `"\"b\""`.

**Comment by wingyplus** [comment]
I read test from https://github.com/line/centraldogma/blob/master/server/src/test/java/com/linecorp/centraldogma/server/internal/api/ContentServiceV1Test.java#L276. Looks like it's intention.

**Comment by wingyplus** [comment]
@minwoox Is it possible that `UnmarshalJSON` strip `"` out of content by using `json.Unmarshal`? 

ref: https://github.com/line/centraldogma-go/blob/master/content_service.go#L88

**Comment by minwoox** [comment]
@wingyplus Sorry about the late response. Was on a business trip and couldn't take care of this issue.
Let me just reproduce it. Thanks!
BTW, are you using Central Dogma?

**Comment by wingyplus** [comment]
@minwoox I see it using inside LINE Man Team (but another team not my team). And I interesting to use it in my personal project. :)

**Comment by minwoox** [comment]
@wingyplus Ah that's cool! If you want to talk directly, you can use the company slack #help_centraldogma. :-)

**Comment by wingyplus** [comment]
@minwoox Thanks for your guide. :D
